
services:
    sequence_generator.sequence:
        class: Kinulab\SequenceGeneratorBundle\Generator\SequenceGenerator
        public: true
        arguments: ['@sequence_generator.repository']

    Kinulab\SequenceGeneratorBundle\Generator\SequenceGenerator:
        alias: sequence_generator.sequence
        public: false

    sequence_generator.repository:
        class: Kinulab\SequenceGeneratorBundle\Repository\SequenceRepository
        public: true
        arguments: ['@doctrine.orm.entity_manager']

    Kinulab\SequenceGeneratorBundle\Repository\SequenceRepository:
        alias: sequence_generator.repository
        public: false
