Kinulab\SequenceGeneratorBundle\Entity\CustomSequence:
  type: entity
  table: sys_custom_sequence
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    libelle:
      type: string
      nullable: false
    sequence_name:
      type: string
      unique: true
      nullable: false
    prefix:
      type: string
      nullable: true
    suffix:
      type: string
      nullable: true
    increment_length:
      type: integer
      nullable: false
    increment_by:
      type: integer
      nullable: false
    independant_complement:
      type: boolean
      nullable: false
      options:
        default: false
        comment: une séquence indépendante pour chaque couples prefix-suffix unique
    last_run:
        type: datetime_immutable
        nullable: true
    restart_yearly:
      type: boolean
      nullable: false
      options:
        default: false
  oneToMany:
    sub_sequences:
      targetEntity: Kinulab\SequenceGeneratorBundle\Entity\CustomSequenceSub
      mappedBy: custom_sequence
